(define (problem hotel-ext3)
  (:domain hotel)

  (:objects
    h1 h2 h3 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (capacidad h1) 2)
    (= (capacidad h2) 4)
    (= (capacidad h3) 3)
    (orientacion h1 n)
    (orientacion h2 o)
    (orientacion h3 n)

    (= (num-personas r1) 2)
    (= (dia-inicio r1) 5)
    (= (dia-fin r1) 10)
    (dia-de-reserva r1 d5)
    (dia-de-reserva r1 d6)
    (dia-de-reserva r1 d7)
    (dia-de-reserva r1 d8)
    (dia-de-reserva r1 d9)
    (dia-de-reserva r1 d10)
    (preferencia r1 n)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 4)
    (= (dia-fin r2) 8)
    (dia-de-reserva r2 d4)
    (dia-de-reserva r2 d5)
    (dia-de-reserva r2 d6)
    (dia-de-reserva r2 d7)
    (dia-de-reserva r2 d8)
    (preferencia r2 s)

    (= (num-personas r3) 3)
    (= (dia-inicio r3) 25)
    (= (dia-fin r3) 26)
    (dia-de-reserva r3 d25)
    (dia-de-reserva r3 d26)
    (preferencia r3 s)

    (= (num-personas r4) 3)
    (= (dia-inicio r4) 2)
    (= (dia-fin r4) 7)
    (dia-de-reserva r4 d2)
    (dia-de-reserva r4 d3)
    (dia-de-reserva r4 d4)
    (dia-de-reserva r4 d5)
    (dia-de-reserva r4 d6)
    (dia-de-reserva r4 d7)
    (preferencia r4 n)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 8)
    (= (dia-fin r5) 12)
    (dia-de-reserva r5 d8)
    (dia-de-reserva r5 d9)
    (dia-de-reserva r5 d10)
    (dia-de-reserva r5 d11)
    (dia-de-reserva r5 d12)
    (preferencia r5 o)

    (= (num-personas r6) 3)
    (= (dia-inicio r6) 14)
    (= (dia-fin r6) 15)
    (dia-de-reserva r6 d14)
    (dia-de-reserva r6 d15)
    (preferencia r6 n)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 1)
    (= (dia-fin r7) 7)
    (dia-de-reserva r7 d1)
    (dia-de-reserva r7 d2)
    (dia-de-reserva r7 d3)
    (dia-de-reserva r7 d4)
    (dia-de-reserva r7 d5)
    (dia-de-reserva r7 d6)
    (dia-de-reserva r7 d7)
    (preferencia r7 o)

    (= (num-personas r8) 2)
    (= (dia-inicio r8) 7)
    (= (dia-fin r8) 8)
    (dia-de-reserva r8 d7)
    (dia-de-reserva r8 d8)
    (preferencia r8 e)

    (= (num-personas r9) 2)
    (= (dia-inicio r9) 12)
    (= (dia-fin r9) 16)
    (dia-de-reserva r9 d12)
    (dia-de-reserva r9 d13)
    (dia-de-reserva r9 d14)
    (dia-de-reserva r9 d15)
    (dia-de-reserva r9 d16)
    (preferencia r9 s)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 24)
    (= (dia-fin r10) 25)
    (dia-de-reserva r10 d24)
    (dia-de-reserva r10 d25)
    (preferencia r10 o)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (* 0.5 (coste-desperdicio)))))
)