(define (problem hotel-ext2)
  (:domain hotel)

  (:objects
    h1 h2 h3 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (capacidad h1) 2)
    (= (capacidad h2) 4)
    (= (capacidad h3) 3)
    (orientacion h1 o)
    (orientacion h2 n)
    (orientacion h3 s)

    (= (num-personas r1) 2)
    (= (dia-inicio r1) 8)
    (= (dia-fin r1) 10)
    (dia-de-reserva r1 d8)
    (dia-de-reserva r1 d9)
    (dia-de-reserva r1 d10)
    (preferencia r1 n)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 4)
    (= (dia-fin r2) 8)
    (dia-de-reserva r2 d4)
    (dia-de-reserva r2 d5)
    (dia-de-reserva r2 d6)
    (dia-de-reserva r2 d7)
    (dia-de-reserva r2 d8)
    (preferencia r2 n)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 6)
    (= (dia-fin r3) 12)
    (dia-de-reserva r3 d6)
    (dia-de-reserva r3 d7)
    (dia-de-reserva r3 d8)
    (dia-de-reserva r3 d9)
    (dia-de-reserva r3 d10)
    (dia-de-reserva r3 d11)
    (dia-de-reserva r3 d12)
    (preferencia r3 e)

    (= (num-personas r4) 3)
    (= (dia-inicio r4) 21)
    (= (dia-fin r4) 24)
    (dia-de-reserva r4 d21)
    (dia-de-reserva r4 d22)
    (dia-de-reserva r4 d23)
    (dia-de-reserva r4 d24)
    (preferencia r4 o)

    (= (num-personas r5) 3)
    (= (dia-inicio r5) 22)
    (= (dia-fin r5) 24)
    (dia-de-reserva r5 d22)
    (dia-de-reserva r5 d23)
    (dia-de-reserva r5 d24)
    (preferencia r5 e)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 11)
    (= (dia-fin r6) 17)
    (dia-de-reserva r6 d11)
    (dia-de-reserva r6 d12)
    (dia-de-reserva r6 d13)
    (dia-de-reserva r6 d14)
    (dia-de-reserva r6 d15)
    (dia-de-reserva r6 d16)
    (dia-de-reserva r6 d17)
    (preferencia r6 e)

    (= (num-personas r7) 3)
    (= (dia-inicio r7) 6)
    (= (dia-fin r7) 6)
    (dia-de-reserva r7 d6)
    (preferencia r7 n)

    (= (num-personas r8) 3)
    (= (dia-inicio r8) 4)
    (= (dia-fin r8) 6)
    (dia-de-reserva r8 d4)
    (dia-de-reserva r8 d5)
    (dia-de-reserva r8 d6)
    (preferencia r8 e)

    (= (num-personas r9) 1)
    (= (dia-inicio r9) 21)
    (= (dia-fin r9) 27)
    (dia-de-reserva r9 d21)
    (dia-de-reserva r9 d22)
    (dia-de-reserva r9 d23)
    (dia-de-reserva r9 d24)
    (dia-de-reserva r9 d25)
    (dia-de-reserva r9 d26)
    (dia-de-reserva r9 d27)
    (preferencia r9 e)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 12)
    (= (dia-fin r10) 15)
    (dia-de-reserva r10 d12)
    (dia-de-reserva r10 d13)
    (dia-de-reserva r10 d14)
    (dia-de-reserva r10 d15)
    (preferencia r10 n)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar) (coste-orientacion)))
)