(define (problem problema_h7_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 h6 h7 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (= (capacidad h6) 1)
    (= (capacidad h7) 2)
    (orientacion h1 n)
    (orientacion h2 e)
    (orientacion h3 o)
    (orientacion h4 s)
    (orientacion h5 o)
    (orientacion h6 n)
    (orientacion h7 s)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 24)
    (= (dia-fin r1) 25)
    (dia-de-reserva r1 d24)
    (dia-de-reserva r1 d25)
    (preferencia r1 o)

    (= (num-personas r2) 2)
    (= (dia-inicio r2) 6)
    (= (dia-fin r2) 12)
    (dia-de-reserva r2 d6)
    (dia-de-reserva r2 d7)
    (dia-de-reserva r2 d8)
    (dia-de-reserva r2 d9)
    (dia-de-reserva r2 d10)
    (dia-de-reserva r2 d11)
    (dia-de-reserva r2 d12)
    (preferencia r2 o)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 25)
    (= (dia-fin r3) 30)
    (dia-de-reserva r3 d25)
    (dia-de-reserva r3 d26)
    (dia-de-reserva r3 d27)
    (dia-de-reserva r3 d28)
    (dia-de-reserva r3 d29)
    (dia-de-reserva r3 d30)
    (preferencia r3 n)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 20)
    (= (dia-fin r4) 24)
    (dia-de-reserva r4 d20)
    (dia-de-reserva r4 d21)
    (dia-de-reserva r4 d22)
    (dia-de-reserva r4 d23)
    (dia-de-reserva r4 d24)
    (preferencia r4 o)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 5)
    (= (dia-fin r5) 5)
    (dia-de-reserva r5 d5)
    (preferencia r5 n)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 25)
    (= (dia-fin r6) 26)
    (dia-de-reserva r6 d25)
    (dia-de-reserva r6 d26)
    (preferencia r6 s)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 10)
    (= (dia-fin r7) 12)
    (dia-de-reserva r7 d10)
    (dia-de-reserva r7 d11)
    (dia-de-reserva r7 d12)
    (preferencia r7 s)

    (= (num-personas r8) 3)
    (= (dia-inicio r8) 29)
    (= (dia-fin r8) 30)
    (dia-de-reserva r8 d29)
    (dia-de-reserva r8 d30)
    (preferencia r8 s)

    (= (num-personas r9) 1)
    (= (dia-inicio r9) 23)
    (= (dia-fin r9) 24)
    (dia-de-reserva r9 d23)
    (dia-de-reserva r9 d24)
    (preferencia r9 o)

    (= (num-personas r10) 2)
    (= (dia-inicio r10) 1)
    (= (dia-fin r10) 3)
    (dia-de-reserva r10 d1)
    (dia-de-reserva r10 d2)
    (dia-de-reserva r10 d3)
    (preferencia r10 o)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)