(define (problem problema_h5_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (orientacion h1 n)
    (orientacion h2 s)
    (orientacion h3 n)
    (orientacion h4 e)
    (orientacion h5 o)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 13)
    (= (dia-fin r1) 17)
    (dia-de-reserva r1 d13)
    (dia-de-reserva r1 d14)
    (dia-de-reserva r1 d15)
    (dia-de-reserva r1 d16)
    (dia-de-reserva r1 d17)
    (preferencia r1 n)

    (= (num-personas r2) 3)
    (= (dia-inicio r2) 8)
    (= (dia-fin r2) 8)
    (dia-de-reserva r2 d8)
    (preferencia r2 s)

    (= (num-personas r3) 2)
    (= (dia-inicio r3) 9)
    (= (dia-fin r3) 10)
    (dia-de-reserva r3 d9)
    (dia-de-reserva r3 d10)
    (preferencia r3 o)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 25)
    (= (dia-fin r4) 30)
    (dia-de-reserva r4 d25)
    (dia-de-reserva r4 d26)
    (dia-de-reserva r4 d27)
    (dia-de-reserva r4 d28)
    (dia-de-reserva r4 d29)
    (dia-de-reserva r4 d30)
    (preferencia r4 n)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 20)
    (= (dia-fin r5) 24)
    (dia-de-reserva r5 d20)
    (dia-de-reserva r5 d21)
    (dia-de-reserva r5 d22)
    (dia-de-reserva r5 d23)
    (dia-de-reserva r5 d24)
    (preferencia r5 o)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 5)
    (= (dia-fin r6) 5)
    (dia-de-reserva r6 d5)
    (preferencia r6 n)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 25)
    (= (dia-fin r7) 26)
    (dia-de-reserva r7 d25)
    (dia-de-reserva r7 d26)
    (preferencia r7 s)

    (= (num-personas r8) 1)
    (= (dia-inicio r8) 10)
    (= (dia-fin r8) 12)
    (dia-de-reserva r8 d10)
    (dia-de-reserva r8 d11)
    (dia-de-reserva r8 d12)
    (preferencia r8 s)

    (= (num-personas r9) 3)
    (= (dia-inicio r9) 29)
    (= (dia-fin r9) 30)
    (dia-de-reserva r9 d29)
    (dia-de-reserva r9 d30)
    (preferencia r9 s)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 23)
    (= (dia-fin r10) 24)
    (dia-de-reserva r10 d23)
    (dia-de-reserva r10 d24)
    (preferencia r10 o)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)