(define (problem problema_h8_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 h6 h7 h8 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (= (capacidad h6) 1)
    (= (capacidad h7) 2)
    (= (capacidad h8) 1)
    (orientacion h1 e)
    (orientacion h2 o)
    (orientacion h3 s)
    (orientacion h4 o)
    (orientacion h5 n)
    (orientacion h6 s)
    (orientacion h7 n)
    (orientacion h8 s)

    (= (num-personas r1) 2)
    (= (dia-inicio r1) 9)
    (= (dia-fin r1) 10)
    (dia-de-reserva r1 d9)
    (dia-de-reserva r1 d10)
    (preferencia r1 o)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 25)
    (= (dia-fin r2) 30)
    (dia-de-reserva r2 d25)
    (dia-de-reserva r2 d26)
    (dia-de-reserva r2 d27)
    (dia-de-reserva r2 d28)
    (dia-de-reserva r2 d29)
    (dia-de-reserva r2 d30)
    (preferencia r2 n)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 20)
    (= (dia-fin r3) 24)
    (dia-de-reserva r3 d20)
    (dia-de-reserva r3 d21)
    (dia-de-reserva r3 d22)
    (dia-de-reserva r3 d23)
    (dia-de-reserva r3 d24)
    (preferencia r3 o)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 5)
    (= (dia-fin r4) 5)
    (dia-de-reserva r4 d5)
    (preferencia r4 n)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 25)
    (= (dia-fin r5) 26)
    (dia-de-reserva r5 d25)
    (dia-de-reserva r5 d26)
    (preferencia r5 s)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 10)
    (= (dia-fin r6) 12)
    (dia-de-reserva r6 d10)
    (dia-de-reserva r6 d11)
    (dia-de-reserva r6 d12)
    (preferencia r6 s)

    (= (num-personas r7) 3)
    (= (dia-inicio r7) 29)
    (= (dia-fin r7) 30)
    (dia-de-reserva r7 d29)
    (dia-de-reserva r7 d30)
    (preferencia r7 s)

    (= (num-personas r8) 1)
    (= (dia-inicio r8) 23)
    (= (dia-fin r8) 24)
    (dia-de-reserva r8 d23)
    (dia-de-reserva r8 d24)
    (preferencia r8 o)

    (= (num-personas r9) 2)
    (= (dia-inicio r9) 1)
    (= (dia-fin r9) 3)
    (dia-de-reserva r9 d1)
    (dia-de-reserva r9 d2)
    (dia-de-reserva r9 d3)
    (preferencia r9 o)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 30)
    (= (dia-fin r10) 30)
    (dia-de-reserva r10 d30)
    (preferencia r10 e)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)