(define (problem problema_h10_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (= (capacidad h6) 1)
    (= (capacidad h7) 2)
    (= (capacidad h8) 1)
    (= (capacidad h9) 3)
    (= (capacidad h10) 4)
    (orientacion h1 s)
    (orientacion h2 o)
    (orientacion h3 n)
    (orientacion h4 s)
    (orientacion h5 n)
    (orientacion h6 s)
    (orientacion h7 o)
    (orientacion h8 e)
    (orientacion h9 s)
    (orientacion h10 o)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 25)
    (= (dia-fin r1) 30)
    (dia-de-reserva r1 d25)
    (dia-de-reserva r1 d26)
    (dia-de-reserva r1 d27)
    (dia-de-reserva r1 d28)
    (dia-de-reserva r1 d29)
    (dia-de-reserva r1 d30)
    (preferencia r1 n)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 20)
    (= (dia-fin r2) 24)
    (dia-de-reserva r2 d20)
    (dia-de-reserva r2 d21)
    (dia-de-reserva r2 d22)
    (dia-de-reserva r2 d23)
    (dia-de-reserva r2 d24)
    (preferencia r2 o)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 5)
    (= (dia-fin r3) 5)
    (dia-de-reserva r3 d5)
    (preferencia r3 n)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 25)
    (= (dia-fin r4) 26)
    (dia-de-reserva r4 d25)
    (dia-de-reserva r4 d26)
    (preferencia r4 s)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 10)
    (= (dia-fin r5) 12)
    (dia-de-reserva r5 d10)
    (dia-de-reserva r5 d11)
    (dia-de-reserva r5 d12)
    (preferencia r5 s)

    (= (num-personas r6) 3)
    (= (dia-inicio r6) 29)
    (= (dia-fin r6) 30)
    (dia-de-reserva r6 d29)
    (dia-de-reserva r6 d30)
    (preferencia r6 s)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 23)
    (= (dia-fin r7) 24)
    (dia-de-reserva r7 d23)
    (dia-de-reserva r7 d24)
    (preferencia r7 o)

    (= (num-personas r8) 2)
    (= (dia-inicio r8) 1)
    (= (dia-fin r8) 3)
    (dia-de-reserva r8 d1)
    (dia-de-reserva r8 d2)
    (dia-de-reserva r8 d3)
    (preferencia r8 o)

    (= (num-personas r9) 1)
    (= (dia-inicio r9) 30)
    (= (dia-fin r9) 30)
    (dia-de-reserva r9 d30)
    (preferencia r9 e)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 11)
    (= (dia-fin r10) 13)
    (dia-de-reserva r10 d11)
    (dia-de-reserva r10 d12)
    (dia-de-reserva r10 d13)
    (preferencia r10 n)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)