(define (problem hotel-ext4)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 2)
    (= (capacidad h2) 4)
    (= (capacidad h3) 3)
    (= (capacidad h4) 4)
    (orientacion h1 n)
    (orientacion h2 o)
    (orientacion h3 n)
    (orientacion h4 o)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 22)
    (= (dia-fin r1) 22)
    (dia-de-reserva r1 d22)
    (preferencia r1 s)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 18)
    (= (dia-fin r2) 19)
    (dia-de-reserva r2 d18)
    (dia-de-reserva r2 d19)
    (preferencia r2 s)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 24)
    (= (dia-fin r3) 24)
    (dia-de-reserva r3 d24)
    (preferencia r3 n)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 8)
    (= (dia-fin r4) 12)
    (dia-de-reserva r4 d8)
    (dia-de-reserva r4 d9)
    (dia-de-reserva r4 d10)
    (dia-de-reserva r4 d11)
    (dia-de-reserva r4 d12)
    (preferencia r4 o)

    (= (num-personas r5) 3)
    (= (dia-inicio r5) 14)
    (= (dia-fin r5) 15)
    (dia-de-reserva r5 d14)
    (dia-de-reserva r5 d15)
    (preferencia r5 n)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 1)
    (= (dia-fin r6) 7)
    (dia-de-reserva r6 d1)
    (dia-de-reserva r6 d2)
    (dia-de-reserva r6 d3)
    (dia-de-reserva r6 d4)
    (dia-de-reserva r6 d5)
    (dia-de-reserva r6 d6)
    (dia-de-reserva r6 d7)
    (preferencia r6 o)

    (= (num-personas r7) 2)
    (= (dia-inicio r7) 7)
    (= (dia-fin r7) 8)
    (dia-de-reserva r7 d7)
    (dia-de-reserva r7 d8)
    (preferencia r7 e)

    (= (num-personas r8) 2)
    (= (dia-inicio r8) 12)
    (= (dia-fin r8) 16)
    (dia-de-reserva r8 d12)
    (dia-de-reserva r8 d13)
    (dia-de-reserva r8 d14)
    (dia-de-reserva r8 d15)
    (dia-de-reserva r8 d16)
    (preferencia r8 s)

    (= (num-personas r9) 1)
    (= (dia-inicio r9) 24)
    (= (dia-fin r9) 25)
    (dia-de-reserva r9 d24)
    (dia-de-reserva r9 d25)
    (preferencia r9 o)

    (= (num-personas r10) 3)
    (= (dia-inicio r10) 22)
    (= (dia-fin r10) 26)
    (dia-de-reserva r10 d22)
    (dia-de-reserva r10 d23)
    (dia-de-reserva r10 d24)
    (dia-de-reserva r10 d25)
    (dia-de-reserva r10 d26)
    (preferencia r10 n)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)