(define (problem problema_h13_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (= (capacidad h6) 1)
    (= (capacidad h7) 2)
    (= (capacidad h8) 1)
    (= (capacidad h9) 3)
    (= (capacidad h10) 4)
    (= (capacidad h11) 2)
    (= (capacidad h12) 4)
    (= (capacidad h13) 1)
    (orientacion h1 s)
    (orientacion h2 n)
    (orientacion h3 s)
    (orientacion h4 o)
    (orientacion h5 e)
    (orientacion h6 s)
    (orientacion h7 o)
    (orientacion h8 s)
    (orientacion h9 n)
    (orientacion h10 s)
    (orientacion h11 o)
    (orientacion h12 s)
    (orientacion h13 s)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 28)
    (= (dia-fin r1) 28)
    (dia-de-reserva r1 d28)
    (preferencia r1 s)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 6)
    (= (dia-fin r2) 12)
    (dia-de-reserva r2 d6)
    (dia-de-reserva r2 d7)
    (dia-de-reserva r2 d8)
    (dia-de-reserva r2 d9)
    (dia-de-reserva r2 d10)
    (dia-de-reserva r2 d11)
    (dia-de-reserva r2 d12)
    (preferencia r2 s)

    (= (num-personas r3) 2)
    (= (dia-inicio r3) 11)
    (= (dia-fin r3) 12)
    (dia-de-reserva r3 d11)
    (dia-de-reserva r3 d12)
    (preferencia r3 s)

    (= (num-personas r4) 1)
    (= (dia-inicio r4) 23)
    (= (dia-fin r4) 24)
    (dia-de-reserva r4 d23)
    (dia-de-reserva r4 d24)
    (preferencia r4 o)

    (= (num-personas r5) 2)
    (= (dia-inicio r5) 1)
    (= (dia-fin r5) 3)
    (dia-de-reserva r5 d1)
    (dia-de-reserva r5 d2)
    (dia-de-reserva r5 d3)
    (preferencia r5 o)

    (= (num-personas r6) 1)
    (= (dia-inicio r6) 30)
    (= (dia-fin r6) 30)
    (dia-de-reserva r6 d30)
    (preferencia r6 e)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 11)
    (= (dia-fin r7) 13)
    (dia-de-reserva r7 d11)
    (dia-de-reserva r7 d12)
    (dia-de-reserva r7 d13)
    (preferencia r7 n)

    (= (num-personas r8) 3)
    (= (dia-inicio r8) 22)
    (= (dia-fin r8) 27)
    (dia-de-reserva r8 d22)
    (dia-de-reserva r8 d23)
    (dia-de-reserva r8 d24)
    (dia-de-reserva r8 d25)
    (dia-de-reserva r8 d26)
    (dia-de-reserva r8 d27)
    (preferencia r8 e)

    (= (num-personas r9) 1)
    (= (dia-inicio r9) 10)
    (= (dia-fin r9) 12)
    (dia-de-reserva r9 d10)
    (dia-de-reserva r9 d11)
    (dia-de-reserva r9 d12)
    (preferencia r9 e)

    (= (num-personas r10) 2)
    (= (dia-inicio r10) 23)
    (= (dia-fin r10) 25)
    (dia-de-reserva r10 d23)
    (dia-de-reserva r10 d24)
    (dia-de-reserva r10 d25)
    (preferencia r10 s)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)