(define (problem problema_h12_r10)
  (:domain hotel)

  (:objects
    h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 - habitacion
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 - dia
    n s e o - direccion
  )

  (:init
    (= (coste-descartar) 0)
    (= (coste-orientacion) 0)
    (= (coste-desperdicio) 0)
    (= (coste-habitaciones) 0)
    (= (capacidad h1) 3)
    (= (capacidad h2) 3)
    (= (capacidad h3) 1)
    (= (capacidad h4) 4)
    (= (capacidad h5) 2)
    (= (capacidad h6) 1)
    (= (capacidad h7) 2)
    (= (capacidad h8) 1)
    (= (capacidad h9) 3)
    (= (capacidad h10) 4)
    (= (capacidad h11) 2)
    (= (capacidad h12) 4)
    (orientacion h1 n)
    (orientacion h2 s)
    (orientacion h3 n)
    (orientacion h4 s)
    (orientacion h5 o)
    (orientacion h6 e)
    (orientacion h7 s)
    (orientacion h8 o)
    (orientacion h9 s)
    (orientacion h10 n)
    (orientacion h11 s)
    (orientacion h12 o)

    (= (num-personas r1) 1)
    (= (dia-inicio r1) 5)
    (= (dia-fin r1) 5)
    (dia-de-reserva r1 d5)
    (preferencia r1 n)

    (= (num-personas r2) 1)
    (= (dia-inicio r2) 25)
    (= (dia-fin r2) 26)
    (dia-de-reserva r2 d25)
    (dia-de-reserva r2 d26)
    (preferencia r2 s)

    (= (num-personas r3) 1)
    (= (dia-inicio r3) 10)
    (= (dia-fin r3) 12)
    (dia-de-reserva r3 d10)
    (dia-de-reserva r3 d11)
    (dia-de-reserva r3 d12)
    (preferencia r3 s)

    (= (num-personas r4) 3)
    (= (dia-inicio r4) 29)
    (= (dia-fin r4) 30)
    (dia-de-reserva r4 d29)
    (dia-de-reserva r4 d30)
    (preferencia r4 s)

    (= (num-personas r5) 1)
    (= (dia-inicio r5) 23)
    (= (dia-fin r5) 24)
    (dia-de-reserva r5 d23)
    (dia-de-reserva r5 d24)
    (preferencia r5 o)

    (= (num-personas r6) 2)
    (= (dia-inicio r6) 1)
    (= (dia-fin r6) 3)
    (dia-de-reserva r6 d1)
    (dia-de-reserva r6 d2)
    (dia-de-reserva r6 d3)
    (preferencia r6 o)

    (= (num-personas r7) 1)
    (= (dia-inicio r7) 30)
    (= (dia-fin r7) 30)
    (dia-de-reserva r7 d30)
    (preferencia r7 e)

    (= (num-personas r8) 1)
    (= (dia-inicio r8) 11)
    (= (dia-fin r8) 13)
    (dia-de-reserva r8 d11)
    (dia-de-reserva r8 d12)
    (dia-de-reserva r8 d13)
    (preferencia r8 n)

    (= (num-personas r9) 3)
    (= (dia-inicio r9) 22)
    (= (dia-fin r9) 27)
    (dia-de-reserva r9 d22)
    (dia-de-reserva r9 d23)
    (dia-de-reserva r9 d24)
    (dia-de-reserva r9 d25)
    (dia-de-reserva r9 d26)
    (dia-de-reserva r9 d27)
    (preferencia r9 e)

    (= (num-personas r10) 1)
    (= (dia-inicio r10) 10)
    (= (dia-fin r10) 12)
    (dia-de-reserva r10 d10)
    (dia-de-reserva r10 d11)
    (dia-de-reserva r10 d12)
    (preferencia r10 e)
  )

  (:goal
    (and
      (forall (?r - reserva)
        (or (asignada ?r) (descartada ?r))
      )
    )
  )
(:metric minimize (+ (coste-descartar)    (+ (coste-orientacion)       (+ (* 0.25 (coste-habitaciones))          (* 0.5 (coste-desperdicio))))))
)